/*
 * Πιλοτικό dataset. Τα ονόματα προέρχονται από τα ψηφοδέλτια των εκλογών
 * της 25ης Ιουνίου 2023. Περιλαμβάνονται τα οκτώ κόμματα που εξέλεξαν
 * βουλευτές στην αναμέτρηση. Δεν αποτελεί κατάλογο υποψηφίων του 2027.
 */
window.VOTER_GUIDE_DATA = {
  source: "https://www.ertnews.gr/perifereiakoi-stathmoi/kozani/d-makedonia-oi-ekloges-tis-25is-iouniou-2023-me-arithmous/",
  districts: {
    grevena: { label: "Γρεβενών", seats: 1 },
    kastoria: { label: "Καστοριάς", seats: 1 },
    kozani: { label: "Κοζάνης", seats: 4 },
    florina: { label: "Φλώρινας", seats: 2 }
  },
  parties: {
    nd: "Νέα Δημοκρατία",
    syriza: "ΣΥΡΙΖΑ–ΠΣ",
    pasok: "ΠΑΣΟΚ–Κίνημα Αλλαγής",
    kke: "ΚΚΕ",
    elliniki: "Ελληνική Λύση",
    niki: "ΝΙΚΗ",
    plefsi: "Πλεύση Ελευθερίας",
    spartiates: "Σπαρτιάτες"
  },
  candidates: [
    { id:"gia", district:"grevena", party:"nd", name:"Ιωάννης Γιάτσιος", links:[{label:"Vouliwatch",url:"https://vouliwatch.gr/mp/giatsios-ioannis"}], statements:["gia-wildboar"] },
    { id:"sta", district:"grevena", party:"nd", name:"Αθανάσιος Σταυρόπουλος" },
    { id:"kog", district:"grevena", party:"nd", name:"Λαμπρινή Κόγιου" },
    { id:"tzo", district:"grevena", party:"syriza", name:"Φωτεινή Τζουβάρα" },
    { id:"kal", district:"grevena", party:"syriza", name:"Γεώργιος Καλαμαράς" },
    { id:"mpg", district:"grevena", party:"syriza", name:"Χρήστος Μπγιάλας" },
    { id:"sto", district:"grevena", party:"pasok", name:"Ιωάννης Στούπας" },
    { id:"gka", district:"grevena", party:"pasok", name:"Βασίλειος Γκαλόγιαννης" },
    { id:"tsi", district:"grevena", party:"pasok", name:"Αικατερίνη Τσιάνα" },
    { id:"kol", district:"grevena", party:"kke", name:"Ελευθερία Κολίτσα Τσακμακά" },
    { id:"gal", district:"grevena", party:"kke", name:"Δημήτριος Γαλάνης" },
    { id:"kle", district:"grevena", party:"kke", name:"Ιωάννης Κλεισιάρης" },
    { id:"avd", district:"grevena", party:"elliniki", name:"Απόστολος Αβδελάς" },
    { id:"axi", district:"grevena", party:"elliniki", name:"Ελισσάβετ Αξιώτη" },
    { id:"nikg", district:"grevena", party:"niki", name:"Γεώργιος Νικολάου" },
    { id:"sidg", district:"grevena", party:"spartiates", name:"Ευθαλία Σιδηροπούλου" },

    { id:"ant", district:"kastoria", party:"nd", name:"Μαρία Αντωνίου", links:[{label:"Facebook",url:"https://www.facebook.com/maria.antoniou.7906/"},{label:"Βουλή",url:"https://www.hellenicparliament.gr/vouleftes/viografika-stoicheia/?MPId=ef815329-f549-4468-a40f-573c800551b3"}], statements:["ant-fur"] },
    { id:"tzi", district:"kastoria", party:"nd", name:"Ζήσης Τζηκαλάγιας" },
    { id:"kan", district:"kastoria", party:"nd", name:"Αγνή Κανδύλη-Μυκωνιάτη" },
    { id:"tel", district:"kastoria", party:"syriza", name:"Ολυμπία Τελιγιορίδου", links:[{label:"Ιστοσελίδα",url:"https://teligioridou.gr/"}], statements:["tel-gas"] },
    { id:"yag", district:"kastoria", party:"syriza", name:"Κωνσταντίνος Γιαγκόπουλος" },
    { id:"sis", district:"kastoria", party:"syriza", name:"Ιωάννης Σίσιος" },
    { id:"var", district:"kastoria", party:"pasok", name:"Κοσμάς Βαρσάμης" },
    { id:"tsa", district:"kastoria", party:"pasok", name:"Αθηνά Τσαλουκίδου" },
    { id:"nti", district:"kastoria", party:"pasok", name:"Αναστάσιος Ντίνας" },
    { id:"gra", district:"kastoria", party:"kke", name:"Γιαννούλα (Αννέτα) Γραμμένου" },
    { id:"tig", district:"kastoria", party:"kke", name:"Γεώργιος Τίγκας" },
    { id:"sal", district:"kastoria", party:"kke", name:"Αντωνία (Τόνια) Σαλβαρίνα" },
    { id:"pav", district:"kastoria", party:"elliniki", name:"Χρήστος Παύλου" },
    { id:"slt", district:"kastoria", party:"elliniki", name:"Μαρία Σαλτζίδου" },
    { id:"sidk", district:"kastoria", party:"elliniki", name:"Ανέστης Σιδηρόπουλος" },
    { id:"zis", district:"kastoria", party:"niki", name:"Στέλιος Ζήσης" },
    { id:"sar", district:"kastoria", party:"niki", name:"Σοφία Σαρηγιαννίδου" },
    { id:"kou", district:"kastoria", party:"niki", name:"Γεράσιμος Κουσούνης" },
    { id:"ous", district:"kastoria", party:"plefsi", name:"Παναγιώτης Ουσταμπασίδης" },
    { id:"xas", district:"kastoria", party:"spartiates", name:"Πηγή Χασάπη" },

    { id:"kon", district:"kozani", party:"nd", name:"Ευστάθιος Κωνσταντινίδης", links:[{label:"Facebook",url:"https://www.facebook.com/konstantinidisstathis/"}], statements:["kon-transition"] },
    { id:"pap", district:"kozani", party:"nd", name:"Μιχάλης Παπαδόπουλος" },
    { id:"ama", district:"kozani", party:"nd", name:"Γεώργιος Αμανατίδης" },
    { id:"vry", district:"kozani", party:"nd", name:"Παρασκευή Βρυζίδου" },
    { id:"dak", district:"kozani", party:"nd", name:"Γεώργιος Δάκης" },
    { id:"pro", district:"kozani", party:"nd", name:"Ευλαμπία Πρώιου-Βαρζή" },
    { id:"vet", district:"kozani", party:"syriza", name:"Καλλιόπη Βέττα", links:[{label:"Ιστοσελίδα",url:"https://www.vettakalliopi.gr/"}], statements:["vet-lignite"] },
    { id:"kar", district:"kozani", party:"syriza", name:"Θεόδωρος Καρυπίδης" },
    { id:"vat", district:"kozani", party:"syriza", name:"Σωκράτης Βατάλης" },
    { id:"mix", district:"kozani", party:"syriza", name:"Ευθυμία (Έφη) Μιχελάκη" },
    { id:"gks", district:"kozani", party:"syriza", name:"Βασιλική (Βάσω) Γκαστάρη" },
    { id:"pas", district:"kozani", party:"syriza", name:"Κωνσταντίνος Πασσαλίδης" },
    { id:"kuk", district:"kozani", party:"pasok", name:"Παρασκευάς (Πάρις) Κουκουλόπουλος", links:[{label:"Ιστοσελίδα",url:"https://koukoulopoulos.gr/"}], statements:["kuk-timeline"] },
    { id:"zar", district:"kozani", party:"pasok", name:"Λουκάς Ζαρογιάννης" },
    { id:"kam", district:"kozani", party:"pasok", name:"Παναγιώτα Καμαριάδου" },
    { id:"tsr", district:"kozani", party:"pasok", name:"Ελένη Τσιρνάρη" },
    { id:"nik", district:"kozani", party:"pasok", name:"Ισαάκ Νικολαΐδης" },
    { id:"fta", district:"kozani", party:"pasok", name:"Γεώργιος Φτάκας" },
    { id:"kuz", district:"kozani", party:"kke", name:"Θεοδώρα Ματίνα (Τίνα) Κουζιάκη" },
    { id:"moy", district:"kozani", party:"kke", name:"Σταύρος Μωυσιάδης" },
    { id:"dim", district:"kozani", party:"kke", name:"Φωτεινή Δημαράκη" },
    { id:"tri", district:"kozani", party:"kke", name:"Κωνσταντίνος Τριανταφυλλίδης" },
    { id:"the", district:"kozani", party:"kke", name:"Εμμανουήλ Θεοδωρίδης" },
    { id:"egr", district:"kozani", party:"kke", name:"Αβραάμ Έγρες" },
    { id:"lib", district:"kozani", party:"elliniki", name:"Αναστασία Λιβεριάδου" },
    { id:"kot", district:"kozani", party:"elliniki", name:"Ελευθέριος Κωτσιόπουλος" },
    { id:"xei", district:"kozani", party:"elliniki", name:"Κατίνα (Κατερίνα) Χειμωνίδου" },
    { id:"xar", district:"kozani", party:"elliniki", name:"Αναστάσιος Χαραλαμπίδης" },
    { id:"pax", district:"kozani", party:"elliniki", name:"Χαράλαμπος Παπαδόπουλος" },
    { id:"xan", district:"kozani", party:"elliniki", name:"Πέτρος Ξανθόπουλος" },
    { id:"mba", district:"kozani", party:"niki", name:"Κωνσταντίνος Μπαλιάκας" },
    { id:"sism", district:"kozani", party:"niki", name:"Πολυξένη Σισμανίδου" },
    { id:"boz", district:"kozani", party:"niki", name:"Μαρία Μποζίνη" },
    { id:"sam", district:"kozani", party:"niki", name:"Ανέστης Σαμαράς" },
    { id:"pra", district:"kozani", party:"plefsi", name:"Δημήτριος Πράσσας" },
    { id:"kag", district:"kozani", party:"plefsi", name:"Ιφιγένεια Καραγκιουλόγλου" },
    { id:"bar", district:"kozani", party:"plefsi", name:"Γεώργιος Βαρδάκας" },
    { id:"zos", district:"kozani", party:"plefsi", name:"Νίκα Ζωσιμίδου" },
    { id:"xri", district:"kozani", party:"spartiates", name:"Κορνηλία Χριστοφόρου" },

    { id:"pps", district:"florina", party:"nd", name:"Σταύρος Παπασωτηρίου", links:[{label:"Βουλή",url:"https://www.hellenicparliament.gr/Vouleftes/Viografika-Stoicheia/?MPId=4f54b337-5ed4-49e1-8309-b01900d9d1af"},{label:"Facebook",url:"https://www.facebook.com/stavros.papasotiriou/"}], statements:["pps-heating"] },
    { id:"anf", district:"florina", party:"nd", name:"Ιωάννης Αντωνιάδης" },
    { id:"vel", district:"florina", party:"nd", name:"Παυλίνα Βέλτση" },
    { id:"ili", district:"florina", party:"nd", name:"Σοφία Ηλιάδου-Τάχου" },
    { id:"per", district:"florina", party:"syriza", name:"Θεοπίστη (Πέτη) Πέρκα", links:[{label:"Ιστοσελίδα",url:"https://perkapeti.gr/"},{label:"Instagram",url:"https://www.instagram.com/petiperka/"}], statements:["per-transition"] },
    { id:"kwi", district:"florina", party:"syriza", name:"Γεώργιος Κωτακίδης" },
    { id:"bir", district:"florina", party:"syriza", name:"Στέφανος Μπίρος" },
    { id:"kri", district:"florina", party:"syriza", name:"Ειρήνη Κρητικού" },
    { id:"lav", district:"florina", party:"pasok", name:"Λάζαρος Λαβασίδης" },
    { id:"krf", district:"florina", party:"pasok", name:"Διαμαντούλα (Διαμάντω) Κρητικού-Φραντζή" },
    { id:"kard", district:"florina", party:"pasok", name:"Όλγα Καραδάκου" },
    { id:"geo", district:"florina", party:"pasok", name:"Αριστοτέλης (Τέλης) Γεωργιάδης" },
    { id:"vog", district:"florina", party:"kke", name:"Μαρία Βογιατζή" },
    { id:"tor", district:"florina", party:"kke", name:"Παναγιώτα (Γιώτα) Τορλαχίδου" },
    { id:"vys", district:"florina", party:"kke", name:"Ευάγγελος Βυσίνης" },
    { id:"ale", district:"florina", party:"kke", name:"Ευάγγελος Αλεξίου" },
    { id:"gak", district:"florina", party:"elliniki", name:"Δημήτριος Γάκης" },
    { id:"ppl", district:"florina", party:"elliniki", name:"Άννα Παπουλίδου" },
    { id:"tan", district:"florina", party:"niki", name:"Αλεξία Τάντση" },
    { id:"pavf", district:"florina", party:"niki", name:"Βασίλειος Παπαδόπουλος" },
    { id:"xrf", district:"florina", party:"spartiates", name:"Θεόδωρος Χαρατσάρης" }
  ],
  statements: {
    "gia-wildboar": { candidate:"gia", topic:"Αγροτική οικονομία", date:"06/12/2023", title:"Μέτρα για τη διαχείριση του υπερπληθυσμού αγριόχοιρων", summary:"Με κοινοβουλευτική ερώτηση πρότεινε, μεταξύ άλλων, κίνητρα προς θηρευτές, αξιοποίηση του κρέατος και ενίσχυση των ελέγχων για την προστασία κτηνοτρόφων και καταναλωτών.", source:"https://www.hellenicparliament.gr/UserFiles/c0d5184d-7550-4265-8e0b-078e1bc7375a/12436861.pdf" },
    "ant-fur": { candidate:"ant", topic:"Τοπική οικονομία", date:"15/10/2025", title:"Στήριξη εργαζομένων και επιχειρήσεων στον κλάδο της γούνας", summary:"Υποστήριξε δημόσια παρεμβάσεις ενίσχυσης του κλάδου της γουνοποιίας, τον οποίο συνέδεσε με την οικονομία, την επιχειρηματικότητα και την εξωστρέφεια της Καστοριάς.", source:"https://www.facebook.com/maria.antoniou.7906/videos/3133877196795278/" },
    "tel-gas": { candidate:"tel", topic:"Ενέργεια", date:"29/07/2022", title:"Διατήρηση του σχεδιασμού σύνδεσης της Καστοριάς με φυσικό αέριο", summary:"Κατέθεσε κοινοβουλευτική ερώτηση αντιδρώντας σε αλλαγή του σχεδιασμού για τη σύνδεση της Π.Ε. Καστοριάς με το δίκτυο φυσικού αερίου.", source:"https://syriza.gr/h-olympia-teligioridoy-phgainei-sth-boylh-to-thema-me-thn-allagh-schediasmoy-gia-to-fysiko-aerio-sthn-pe-kastorias/" },
    "kon-transition": { candidate:"kon", topic:"Ενέργεια και μετάβαση", date:"07/05/2026", title:"Συνταγματική κατοχύρωση της απολιγνιτοποίησης και της Δίκαιης Μετάβασης", summary:"Πρότεινε να περιληφθούν στη συνταγματική αναθεώρηση ειδικές προβλέψεις για περιοχές που επηρεάζονται από μεγάλες οικονομικές, κοινωνικές και περιβαλλοντικές αλλαγές.", source:"https://xronos-kozanis.gr/protasi-stathi-konstantinidi-gia-syntagmatiki-katochyrosi-tis-apolignitopoiisis-kai-tis-dikaiis-metavasis/" },
    "vet-lignite": { candidate:"vet", topic:"Ενέργεια και εργασία", date:"26/06/2026", title:"Κριτική στην ταχύτητα και στον σχεδιασμό της απολιγνιτοποίησης", summary:"Χαρακτήρισε τη μετάβαση αιφνίδια και βίαιη και υποστήριξε ότι εντείνει την οικονομική συρρίκνωση και την εξάρτηση από εισαγόμενο φυσικό αέριο.", source:"https://syriza.gr/kalliopi-vetta-i-periochi-tis-dytikis-makedonias-echei-ginei-koinoniko-peirama-tis-kyvernisis-tis-n-d-synentefxi-sto-kokkino-gia-tin-apolignitopoiisi-s/" },
    "kuk-timeline": { candidate:"kuk", topic:"Ενέργεια και εργασία", date:"22/09/2025", title:"Παράταση του χρονοδιαγράμματος απόσυρσης των λιγνιτικών μονάδων", summary:"Ζήτησε παράταση του χρονοδιαγράμματος απολιγνιτοποίησης, συνδέοντας την πρόταση με τις οικονομικές και κοινωνικές επιπτώσεις στη Δυτική Μακεδονία.", source:"https://energypress.gr/news/apolignitopoiisi" },
    "pps-heating": { candidate:"pps", topic:"Ενέργεια", date:"22/10/2024", title:"Υπέρ της συμφωνίας για την τηλεθέρμανση Αμυνταίου", summary:"Υποστήριξε ότι η σχετική συμφωνία αντιμετωπίζει το χρόνιο πρόβλημα προμήθειας θερμικής ενέργειας στο Αμύνταιο.", source:"https://www.ertnews.gr/perifereiakoi-stathmoi/florina/florina-st-papasotiriou-i-symfonia-gia-tin-tilethermansi-antimetopizei-to-xronio-provlima-promitheias-thermikis-energeias-sto-amyntaio/" },
    "per-transition": { candidate:"per", topic:"Ενέργεια και εργασία", date:"21/07/2021", title:"Κριτική στην απολιγνιτοποίηση χωρίς επαρκές σχέδιο μετάβασης", summary:"Υποστήριξε ότι η μείωση της λιγνιτικής δραστηριότητας προχωρούσε χωρίς επαρκή σχεδιασμό για την απασχόληση και την αποκατάσταση των λιγνιτικών περιοχών.", source:"https://www.ertnews.gr/perifereiakoi-stathmoi/florina/florina-p-perka-oi-lignitikes-perioches-katarreoyn-ki-aytoi-kompazoyn-oti-einai-filoperivallontikoi/" }
  }
};
